// OPERATIONS ACTIONS
export const SAVE_OPERATIONS_PLANNED = 'SAVE_OPERATIONS_PLANNED';
export const SAVE_OPERATIONS_DONE = 'SAVE_OPERATIONS_DONE';
export const REQUEST_OPERATIONS = 'REQUEST_OPERATIONS';
export const RECEIVE_OPERATIONS = 'RECEIVE_OPERATIONS';
export const SET_SORT_TYPE = 'SET_SORT_TYPE';
